name: "next-${STAGE}"
services:
  node:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: ${STAGE}
    restart: always
    env_file: .env.${STAGE}
    ports:
      - "${HOST_PORT}:${PORT}"
