import "@/assets/styles/globals.css";

import HelloLayout from "@/layouts/HelloLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children, params }) {
  return <HelloLayout params={params}>{children}</HelloLayout>;
}
