name: Next CI with Docker

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy for staging
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git checkout staging
            git pull
            bash scripts/deploy/deploy.sh ${{ secrets.SERVER_PROJECT_PATH }} staging

      - name: Deploy for main
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git checkout main
            git pull
            bash scripts/deploy/deploy.sh ${{ secrets.SERVER_PROJECT_PATH }} production
